apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: translation-uploads
  namespace: whispertrans
spec:
  accessModes:
    - ReadWriteOnce   # kind uses local-path which only supports RWO
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: translation-results
  namespace: whispertrans
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
